#!/usr/bin/env bash

CI=true
# Find the directory where setup.sh is
# This is relative path to the setup.sh script
CLI_CONFIG_ROOT=`dirname $0`

# Goto config dir
cd $CLI_CONFIG_ROOT

# Convert CLI_CONFIG_ROOT to absolute path
CLI_CONFIG_ROOT=`pwd`

# setup bash-oo-framework
. "$CLI_CONFIG_ROOT/bash-oo-framework/lib/oo-bootstrap.sh"

import util/log

namespace cliConfig
Log::AddOutput cliConfig INFO

Log "CLI-CONFIG: Starting install... $(UI.Powerline.ThumbsUp)"

# load cli-config env variables
. $CLI_CONFIG_ROOT/scripts/env.sh

# try and clean old installation
Log "CLI-CONFIG: Trying to clean old installation: $(UI.Color.Blue)$CLI_CONFIG_ROOT/current$(UI.Color.Default)"
rm -rf "$CLI_CONFIG_ROOT/current" > /dev/null 2> /dev/null || true

# Create installation folder not exists
Log "CLI-CONFIG: Creating new installation location: $(UI.Color.Blue)$CLI_CONFIG_ROOT/current$(UI.Color.Default)"
mkdir current
mkdir $CLI_CONFIG_TOOLS_LOCATION

# Download antigen into src folder
Log "CLI-CONFIG: Installing antigen plugin manager"
curl -L git.io/antigen > $CLI_CONFIG_TOOLS_LOCATION/antigen.zsh

Log "CLI-CONFIG: Installing programs"
printf "# [Autogenerated - do not edit: at `date`] CLI-Config Install configuration\n# --------" >> $CLI_CONFIG_PROGRAMS_CONF
# Note: Comment out any program that you don't want to be installed
. $CLI_CONFIG_ROOT/scripts/install.ohmyzsh.sh
. $CLI_CONFIG_ROOT/scripts/install.nvm.sh
. $CLI_CONFIG_ROOT/scripts/install.pyenv.sh
. $CLI_CONFIG_ROOT/scripts/install.dotnet.sh

currentOs=`uname -s`
if [ $currentOs = "Linux" ]; then
    # Log 'You are on linux'
    # TODO: check if we are specifically on Ubuntu
    . $CLI_CONFIG_ROOT/scripts/os-specific-setup.ubuntu.sh
elif [ $currentOs = "Darwin" ]; then
    # Log 'Mac huh'
    . $CLI_CONFIG_ROOT/scripts/os-specific-setup.darwin.sh
else
    Log 'what realm is this?'
fi

# generate main config script
echo >> $CLI_CONFIG_PROGRAMS_CONF
cat $CLI_CONFIG_ROOT/templates/programs.conf.sh >> $CLI_CONFIG_PROGRAMS_CONF

zshPath=`which zsh`
# set ~/.zshrc to default profile
(rm ~/.zshrc ~/.zshrc.zwc 2> /dev/null || true) && ln -s $CLI_CONFIG_ROOT/profiles/default/.zshrc ~/.zshrc

printf "\n\n\n"
echo "$(UI.Color.Blue)CLI-CONFIG Installation complete! $(UI.Powerline.ThumbsUp)"
echo "$(UI.Color.Default)$(UI.Powerline.OK)$(UI.Color.Blue) You are using cli-config now!"
echo "$(UI.Color.Default)$(UI.Powerline.OK)$(UI.Color.Blue) Symlinked ~/.zshrc to default cli-config profile."
echo "$(UI.Color.Default)$(UI.Powerline.ArrowRight)$(UI.Color.Blue) Note: Your default shell should be '$zshPath'. (Use chsh to change it)"

printf "\n\nEnjoy! Made with $(UI.Powerline.Heart)\n- Saurav $(UI.Color.Default)\n"