name: 'ci'

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          lint_output=$(bash package.sh lint)
          if [ "${lint_output}" != "" ]; then
            echo 'error linting following files'
            echo ${lint_output}
            exit 1
          fi

