name: 'ci'

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          lint_output=$(docker run --rm -u "$(id -u):$(id -g)" -v "$PWD:/mnt" -w /mnt mvdan/shfmt:v3.5.1-alpine -i 2 -l -w src/**/*.zsh)
          if [ "${lint_output}" != "" ]; then
            echo 'error linting following files'
            echo ${lint_output}
            exit 1
          fi

