name: 'ci'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
        name: Checkout to PR Branch

      - name: Setup Deps
        run: sudo apt update -y && sudo apt install --no-install-recommends -y zsh

      - name: Sync setup.sh and cli-config
        run: |
           sync_output=$(diff cli-config setup.sh > /dev/null; echo $?)
           if [ "${sync_output}" = "1" ]; then
             diff cli-config setup.sh
           fi
           exit $sync_output

      - name: Lint Project
        continue-on-error: true
        run: |
          lint_output=$(bash package.sh lint)
          if [ "${lint_output}" != "" ]; then
            echo 'error linting following files'
            echo ${lint_output}
            exit 1
          fi

      - name: Run Tests
        run: |
          bash package.sh test
          test_exit_code=$(echo $?)
          exit ${test_exit_code}

